// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrqitiqgcmrinfnxdjlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycWl0aXFnY21yaW5mbnhkamxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTA1ODYsImV4cCI6MjA1NTg2NjU4Nn0.fYhplo3JHv3ZfB3eDm764B6grDyFC0YLSO843HcXqHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);